CC=g++

all: sqlite3 client server 

sqlite3: sqlite3.c 
	$gcc sqlite3.c -c 

client: client.cpp
	$(CC) client.cpp -o client 

server: server.cpp
	$(CC) server.cpp -std=c++11 -ldl -pthread sqlite3.o -o server 
 

